/**
 * Build script to inline WASM file as base64
 * This avoids runtime file system operations which are not allowed
 * for verified n8n community nodes.
 */

const fs = require('fs');
const path = require('path');

const wasmPath = path.join(__dirname, '..', 'nodes', 'Mq', 'wasm', 'mq_wasm_bg.wasm');
const outputPath = path.join(__dirname, '..', 'nodes', 'Mq', 'wasm-data.ts');

// Read the WASM file
const wasmBuffer = fs.readFileSync(wasmPath);
const base64 = wasmBuffer.toString('base64');

// Generate TypeScript module
const content = `/**
 * Auto-generated file - DO NOT EDIT
 * Contains the mq WASM module as base64-encoded data
 * Generated by scripts/inline-wasm.js
 */

export const WASM_BASE64 = '${base64}';

export function getWasmBuffer(): Uint8Array {
  const binaryString = atob(WASM_BASE64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}
`;

fs.writeFileSync(outputPath, content);
console.log(`Generated ${outputPath} (${(base64.length / 1024).toFixed(1)} KB base64)`);
